### ISSUE TITLE
Downloaded files need to be unblocked

### ISSUE THREAD

**Issue by cunninghamp** [cunninghamp/ExchangeAnalyzer#32]
Reported on Reddit:
https://www.reddit.com/r/exchangeserver/comments/40ujp8/first_beta_of_exchange_analyzer_is_available/

Call this out in documentation, and also consider signing all the scripts for each release.

**Comment by bdesmond** [comment]
I don't think signing it will affect the block issue. That's because it comes from an Internet zone.

Signing is kind of complicated - somebody will need to put their name or a corporate entity on the signature. I can envision liability issues coming along with that. It also puts a single point of failure on the release process as only one person can issue a new release.

**Comment by swngdnz** [comment]
+1

**Comment by cunninghamp** [comment]
Will make a documentation improvement then.

**Comment by cunninghamp** [comment]
This has been added to README.MD.
